-- =====================================================================
-- 8130 APP — standalone warehouse orders + order_number on required parts
-- =====================================================================
-- 1. call_required_parts.order_number — optional PO/reference text the
--    warehouse worker can attach to an ordered item. Edited only from
--    RequiredPartDetailPage; not shown anywhere else.
-- 2. warehouse_orders — a "הזמנת מחסן כללית" not tied to any service
--    call. Each order has a display_id "WO-YY-NNNN" generated by the
--    same year-resetting pattern as service_calls.
-- 3. call_required_parts.warehouse_order_id — link rows to a warehouse
--    order instead of (xor) a service call. Exactly one of call_id /
--    warehouse_order_id must be set.
-- =====================================================================

-- 1. order_number on required parts
alter table public.call_required_parts
  add column order_number text;

-- 2. warehouse_orders
create sequence public.warehouse_order_year_seq start with 1;

create table public.warehouse_orders (
  id          uuid primary key default gen_random_uuid(),
  display_id  text not null unique,                                    -- "WO-26-0001"
  created_by  integer references public.employees(employee_number) on delete set null,
  created_at  timestamptz not null default now()
);

create index warehouse_orders_created_at_idx on public.warehouse_orders (created_at desc);

create or replace function public.fn_assign_warehouse_order_display_id()
returns trigger
language plpgsql
as $$
declare
  yy text;
  nn integer;
begin
  yy := to_char(now() at time zone 'Asia/Jerusalem', 'YY');
  nn := nextval('public.warehouse_order_year_seq');
  new.display_id := format('WO-%s-%s', yy, lpad(nn::text, 4, '0'));
  return new;
end;
$$;

create trigger trg_warehouse_orders_display_id
  before insert on public.warehouse_orders
  for each row
  when (new.display_id is null)
  execute function public.fn_assign_warehouse_order_display_id();

alter table public.warehouse_orders enable row level security;
create policy "anon read"
  on public.warehouse_orders for select to anon, authenticated using (true);
-- Writes go through the warehouse-actions edge function with the service role.

-- 3. link call_required_parts to warehouse_orders
alter table public.call_required_parts
  add column warehouse_order_id uuid references public.warehouse_orders(id) on delete cascade;

alter table public.call_required_parts
  alter column call_id drop not null;

-- Exactly one parent must be set. Either the row belongs to a service
-- call or to a standalone warehouse order — never both, never neither.
alter table public.call_required_parts
  add constraint call_required_parts_one_parent
  check ((call_id is null) <> (warehouse_order_id is null));

create index call_required_parts_warehouse_order_idx
  on public.call_required_parts (warehouse_order_id)
  where warehouse_order_id is not null;
